### ISSUE TITLE
Sign up page responsiveness 

### ISSUE THREAD

**Issue by Vanshika-73** [Vanshika-73/Proshop#1]

**Comment by Pinaka-Pani-18** [comment]
Hi @Vanshika-73, I would like to work on this issue, but the link you added in your bio isn't working to view a preview of the sign-up page I need to work on.

**Comment by Vanshika-73** [comment]
https://proshop-five-beta.vercel.app/register 
Try out this link

**Comment by Vanshika-73** [comment]
https://proshop-five-beta.vercel.app/register (try this one & let me know if worked).
if worked..work on the issue and generate a pr

**Comment by Pinaka-Pani-18** [comment]
> https://proshop-git-main-vanshika-73.vercel.app/ (try this one & let me know if worked). if worked..work on the issue and generate a pr

yes, its working... assign this issue to me. After fixing this issue, I will make a PR.

**Comment by Pinaka-Pani-18** [comment]
while running the website, I am getting the following error:
![image](https://github.com/Vanshika-73/Proshop/assets/102857774/55a75ab9-1553-4668-aa91-7ef264f16ba9)
Do you How to solve it?

**Comment by Vanshika-73** [comment]
run the command- npm i styled-componemts.
Hope it solves the problem.

**Comment by Vanshika-73** [comment]
run the command- npm i styled-componemts.
Hope it solves the problem.

**Comment by Pinaka-Pani-18** [comment]
> run the command- npm i styled-componemts. Hope it solves the problem.

yeah, I solved it few minutes ago. Thanks for the help.

**Comment by Pinaka-Pani-18** [comment]
@Vanshika-73 I have made a PR. please review it...

**Comment by Vanshika-73** [comment]
Check comments

**Comment by Vanshika-73** [comment]
Great work @Pinaka-Pani-18. Merging your PR.

**Comment by Pinaka-Pani-18** [comment]
> Great work @Pinaka-Pani-18. Merging your PR.

Thank you @Vanshika-73
