### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by Vanshika-73** [Vanshika-73/Proshop#12]
on reloading the site, it shows 404 error. Need to resolve that.

**Comment by marinoffDev** [comment]
hey
can you assign this to me?

**Comment by marinoffDev** [comment]
@Vanshika-73 could this be a Vercel configuration issue? Reading from their docs regarding this:

> The path you are accessing was not found in the Build Outputs of your Deployment. If you want to view your Build Outputs directly, you can turn on the [Directory Listing](https://vercel.com/docs/edge-network/directory-listing)

**Comment by Vanshika-73** [comment]
heyy @marinoffDev , I have enable advanced option but still facing that 404 error. If you want to go ahead with this issue, i guess there is a need of index.js file in every folder. Will you create those?
