### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by adityadeshpande09** [Vanshika-73/Proshop#16]
Add license for the project.
Can I work on this ?

**Comment by Vanshika-73** [comment]
what do you mean by license? Can you please explain? @adityadeshpande09

**Comment by Vanshika-73** [comment]
oh okay. will it be some code or md file?

**Comment by Vanshika-73** [comment]
Assigned. go ahead.

**Comment by adityadeshpande09** [comment]
> oh okay. will it be some code or md file?

It would be a .md file
