### ISSUE TITLE
Login page responsiveness

### ISSUE THREAD

**Issue by Vanshika-73** [Vanshika-73/Proshop#2]
Login pages is left to be responsive

**Comment by Rahul-jain-01** [comment]
Hey @Vanshika-73 I can do this. Can you assign this to me
Thank you

**Comment by Vanshika-73** [comment]
Go Ahead.

**Comment by Rahul-jain-01** [comment]
Hey @Vanshika-73 is there a problem with my PR?

**Comment by Vanshika-73** [comment]
Are you working on it? @Rahul-jain-01

**Comment by Rahul-jain-01** [comment]
Yes, I'm working on it. But I am somewhat stuck :(

**Comment by Vanshika-73** [comment]
where? you can take help from register.jsx file. @Pinaka-Pani-18 has worked very well on its responsiveness. coding is almost same for both register and login page. Sync your forked repository, you will get the updated code.

**Comment by Rahul-jain-01** [comment]
Thank you, I will make the changes.
